DROP TABLE IF EXISTS project_category;

DROP TABLE IF EXISTS funder;

DROP TABLE IF EXISTS project_owner;

DROP TABLE IF EXISTS fundraiser;

DROP TABLE IF EXISTS project;

DROP TABLE IF EXISTS reward;

DROP TABLE IF EXISTS fund;


CREATE TABLE project_category
(
       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name VARCHAR(50) UNIQUE NOT NULL,
       description VARCHAR(1000) NOT NULL
);

CREATE TABLE funder
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(50) NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15),
    email     VARCHAR(25) UNIQUE NOT NULL
);


CREATE TABLE project_owner
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(50) NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15) NOT NULL,
    email     VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE project
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    image_link VARCHAR(1000),
    video_link VARCHAR(1000),
    project_owner_id INT NOT NULL,
    project_category_id INT NOT NULL,
    FOREIGN KEY (project_owner_id) REFERENCES  project_owner(id),
    FOREIGN KEY (project_category_id) REFERENCES project_category(id)
);


CREATE TABLE reward
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    quota INT,
    minimum_fund_amount BIGINT NOT NULL,
    estimated_delivery_date DATE NOT NULL,
    project_id INT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES project(id)

);

CREATE TABLE fundraiser
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    goal_amount BIGINT NOT NULL,
    project_id INT NOT NULL,
    FOREIGN KEY (project_id) REFERENCES project(id)
);

CREATE TABLE fund
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_amount BIGINT NOT NULL,
    funder_id INT NOT NULL,
    reward_id INT NOT NULL,
    project_id INT NOT NULL,
    fundraiser_id INT NOT NULL,
    FOREIGN KEY (funder_id) REFERENCES funder (id),
    FOREIGN KEY (reward_id) REFERENCES reward (id),
    FOREIGN KEY (project_id) REFERENCES project(id),
    FOREIGN KEY (fundraiser_id) REFERENCES fundraiser(id)
);


-- ////////////////////////////////////////////////////////////////////////////
--  Sample static test values
-- ////////////////////////////////////////////////////////////////////////////

INSERT INTO project_category(name,description)
VALUES ('ART', 'Big things have small beginnings, discover the art projects and help with their small beginnings'),
       ('FILM','Big things have small beginnings, discover the film and video projects and help with their small beginnings'),
       ('GAMES','Big things have small beginnings, discover the game projects and help for their small beginning'),
       ('PUBLISHING', 'Big things have small beginnings, discover the book and magazines projects and help with their small beginnings'),
       ('ILLUSTRATION', 'Big things have small beginnings, discover fascinating illustration projects and help with their small beginnings'),
       ('DESIGN & TECHNOLOGY', 'While technology is evolving day by day, you can help the creators to build the future with you by discovering the design & tech projects'),
       ('CRAFT', 'The world needs creativity to feel better, you can start to feel better by discovering the craft projects');


INSERT INTO funder(fullname, gender, age, phone, email)
VALUES ('Yoshio Berg','MALE', null,'(626) 515-8654','yoshioberg@google.net'),
       ('Claire Ayers','FEMALE', 33 ,'1-733-913-2645','claireayers@icloud.couk'),
       ('Gretchen Pope', 'FEMALE', 45,null,'gretchenpope@icloud.org'),
       ('Anjolie Velazquez', null, 53,'1-338-722-1385','anjolievelazquez6177@yahoo.couk'),
       ('Oscar Briggs',null, null,'(993) 318-7243','oscarbriggs@aol.ca'),
       ('Susan Duffy','FEMALE', 47, '(878) 542-5440','susanduffy@hotmail.edu'),
       ('Zahir Spencer','MALE', 58, '(256) 395-2653','zahirspencer@yahoo.net'),
       ('Kai Hensley',null, 25, '1-339-855-8890','kaihensley2102@icloud.org'),
       ('Slade Riggs','MALE', 38, null,'sladeriggs4827@hotmail.ca'),
       ('Wallace Peters','MALE', 49, '1-656-880-6680','wallacepeters7848@hotmail.edu');


INSERT INTO project_owner (fullname,gender, age, phone,email)
VALUES
    ('Avram Beard',null, null,'1-927-725-6841','avrambeard@yahoo.edu'),
    ('Christopher Calhoun','MALE',null ,'(976) 532-7572','christophercalhoun9409@yahoo.edu'),
    ('Basia Stanley','FEMALE', 23,'(775) 750-7113','basiastanley9712@icloud.ca'),
    ('Piper Barlow','MALE', 25,'1-495-118-4563','piperbarlow8322@hotmail.edu'),
    ('Kennan Hale',null, 32,'1-619-304-0947','kennanhale2315@yahoo.edu');


INSERT INTO project (name,description,image_link,video_link,project_category_id,project_owner_id)
VALUES
    ('eget tincidunt dui augue','nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.',null,null,7,3),
    ('et nunc. Quisque ornare','dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus.',null,null,4,1),
    ('ipsum. Suspendisse sagittis. Nullam','dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare',null,null,2,4),
    ('pede, malesuada vel, venenatis','imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,',null,null,6,4),
    ('nec, imperdiet nec, leo.','quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum',null,null,3,4);


INSERT INTO reward (name,description,quota,minimum_fund_amount,estimated_delivery_date,project_id)
VALUES
    ('eget tincidunt dui augue','nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.',628,446407,'May , 2022',3),
    ('et nunc. Quisque ornare','dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus.',521,80995,'April , 2022',1),
    ('ipsum. Suspendisse sagittis. Nullam','dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare',null,425576,'July , 2022',4),
    ('pede, malesuada vel, venenatis','imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,',483,349900,'February , 2022',3),
    ('nec, imperdiet nec, leo.','quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum',null,464639,'November , 2022',4),
    ('cursus. Nunc mauris elit,','eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis',74,475125,'March , 2022',2),
    ('in, cursus et, eros.','ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla',57,15487,'November , 2022',4),
    ('a, facilisis non, bibendum','et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque.',447,18041,'March , 2022',4),
    ('dictum eu, eleifend nec,','nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis',161,389530,'June , 2022',5),
    ('In nec orci. Donec','mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis',661,43305,'June , 2022',3);

INSERT INTO fund (fund_amount,funder_id,reward_id, project_id, fundraiser_id)
VALUES
    (4015,10,9,1,3),
    (8631,6,2,2,2),
    (5337,9,9,3,5),
    (4111,4,2,4,4),
    (6404,6,10,5,4),
    (6958,7,9,3,1),
    (1634,7,6,2,2),
    (2174,7,8,1,3),
    (5328,2,3,5,5),
    (7881,3,4,4,2),
    (7716,7,8,2,1),
    (508,6,8,1,4),
    (1312,4,5,3,3),
    (6128,9,2,4,2),
    (5821,5,4,5,1);

INSERT INTO fundraiser (start_date,end_date,goal_amount,project_id)
VALUES
    ('2021-11-30','2022-04-27',29883,5),
    ('2022-01-29','2022-03-28',70300,1),
    ('2022-01-24','2022-05-11',23031,1),
    ('2021-12-21','2022-05-6',27670,5),
    ('2022-01-8','2022-05-15',33503,4);


